server:
  servlet:
    context-path: /api/admin
  port: 9991
spring:
  config:
    import:
      - classpath:config/${spring.profiles.active}/flyway.yml
      - classpath:config/${spring.profiles.active}/knife4j.yml
      - classpath:config/${spring.profiles.active}/oss.yml
      - classpath:config/${spring.profiles.active}/mybatis-flex.yml
      - classpath:config/${spring.profiles.active}/mysql.yml
      - classpath:config/${spring.profiles.active}/page-helper.yml
      - classpath:config/${spring.profiles.active}/redis.yml
      - classpath:config/${spring.profiles.active}/sa-token.yml